### ISSUE TITLE
Bug: Issues with multiple buffers

### ISSUE THREAD

**Issue by Petemir** [kjk/edna#1]
**Describe the bug**

Hello! I saw your comment recently on HN about your tool. First of all, thank you for your contribution; I share some of the pain points that have motivated you to fork heynote so I really liked this app.

That said, after some brief testing (which sadly makes it unusable for my case, namely 4. and 5.), I noticed a few bugs  here and there, all of them related to the multiple buffers. For simplicity I'll state them in the same issue, but let me know if you prefer me to create different issues for them (or to just close this issue :) ).

The problems are:

1. After I create new buffers and assign them shortcuts, when I delete any of them, the shortcut remains assigned to the buffer. So if I switch back to the scratch (`Alt+1`), I can still do `Alt+x`, and then the "Opening BUFFER_NAME" modal appears. It's possible to get out of it by doing `Ctrl+k` and opening the scratch (or any other valid buffer) again. I would expect the shortcut to be unassigned after buffer deletion.

1.1 I don't know if it is related to 1, so I write it as a subitem, but after deleting a buffer the metadata file is not updated.

3. Switching buffers creates some type of problems with the theme. I am not exactly sure how to explain it, but I think it can be reproduced putting dark mode in buffer 1, switching to buffer 2, putting light mode there, and start switching between the different buffers. The theming remains inconsistent, with some parts showing dark, others light, the buffer appearing in dark when the option in the settings says light, etc. I would expect the theme to be consistent when switching buffers (also, it would be nice to know if the theme applies to each buffer, or to the whole app, which is not clear at the moment given the described bug).

4. If I modify one of the buffer files externally, Edna does not reflect the changes. This doesn't happen with heynote, which shows the changes (almost) instantly.

5. I guess both of the following problems are related to localStorage (and maybe 4 is, too), so I am unsure if they are fixable in Edna:

5.1 If a buffer file is a symlink (i.e., pointing to a file somewhere else), Edna cannot open it. 
5.2 If a buffer file is a hardlink (i.e., the same file in two different directories), the hardlink disappears as soon as there is any modification on Edna. Maybe the file is recreated on save, instead of updated? That would mean that the buffer file now points to a new file, so it stops modifying the other hardlinked one. 

One workaround to 5.1 would be to make the buffer file the original one and then point the file in the other directory to Edna's copy, but given 5.2 (i.e., recreation of the file) I am not sure if that would work (although a symlink points to a name and not to an inode, so maybe it does work :thinking: ).

Sorry for the long text, and let me know if you need any other details. Thanks!

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Version: 1.2

**Comment by kjk** [comment]
https://github.com/kjk/edna/commit/40f462baf5a22cb6ddd499f45d066ffdd64aeae5

**Comment by kjk** [comment]
I fixed 1, 3 and 4.

I'm not sure about 4 - you really shouldn't be editing the same file in Edna and externally. 

I made it work by checking every 5 seconds to see if the file has changed on disk and reload in Edna if it did. You can break it (in the sense of loosing some updates) if you switch between Edna and external editor quickly enough, but like I said, I don't see a legitimate reason to be doing it.

There's nothing I can do about symlinks or hardlinks - browser APIs don't support them.

Then again I don't see a use case for that. You can probably symlink TO Edna files, but Edna cannot be symlinks or hardlinks to other files.

**Comment by Petemir** [comment]
Yes, I understand my use-case is peculiar, but what you did is more than enough. Thanks!
