### ISSUE TITLE
Bug: Right Click and Stuck

### ISSUE THREAD

**Issue by thomasklwong** [kjk/edna#11]
**Describe the bug**

**To Reproduce**
1. Go to https://edna.arslexis.io/#scratch
2. Right click anywhere to display the context menu
3. Click anywhere outside of the context menu
4. Context menu does not close

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Failed on Mac Sonoma 14.5, Floorp 11.14.1. user agent string `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0`

Worked on Mac Sonoma 14.5, Firefox 127.0.2. user agent string `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0`

**Comment by kjk** [comment]
Can reproduce in Floorp on Windows. Somehow click handler on overlay doesn't take and also mouseover handler in Menu seems ignored.

Possibly related to z order.

I'm tempted to say that is a Floorp bug if it works in other browsers.

I can try to fix the overlay by e.g. installing click handler on body or using clickoutside action.

Not sure how to fix the Menu. Also installed mouseover handler on body?
