### ISSUE TITLE
Bug: Some fonts don't work

### ISSUE THREAD

**Issue by SlyBouhafs** [kjk/edna#19]
**Describe the bug**
When changing the fonts, i noticed that some fonts that have spaces in their names do not actually work.

**To Reproduce**
1. Go to 'Settings'
2. Choose a font with a space in its name
3. Nothing happens

**Desktop :**
 - OS: Windows 11

**Additional context**
What I noticed, is that in the CSS the font name isn't surrounded by quotation marks, when i put the font name between quotation marks, it actually worked.

**Comment by kjk** [comment]
Which browser? Which font?

I tested on Chrome with few fonts and it worked. Default Windows font is "Cascadia Mono" and it has space in the name.

The code for setting this is in CodeMirror so I would be surprised it was broken.

**Comment by SlyBouhafs** [comment]
The fonts i tried are FiraCode NF and JetBrainsMono NF, I am using brave version 1.67.123 based on Chromium: 126.0.6478.126 (Official Build) (64-bit)
![image](https://github.com/kjk/edna/assets/1410462/032c5cb0-0028-47a2-846f-ef0484230f91)
