### ISSUE TITLE
Bug: "Move notes from browser to directory" only moves "scratch"

### ISSUE THREAD

**Issue by benoitv-code** [kjk/edna#20]
**Describe the bug**

Opening the app and clicking on "Move notes from browser to directory" only transfers "scratch", and not "daily journal" nor "inbox"

**To Reproduce**
1. Open the app
2. Click on "Move notes from browser to directory"
3. See CTRL+p only shows "scratch" being accessible

**Expected behavior**
All "notes" should be transfered

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.8 e3fdfa3

**Comment by kjk** [comment]
There were some bugs in moving. I just re-checked and it works for me.
