### ISSUE TITLE
Feature request: Auto-save on close

### ISSUE THREAD

**Issue by benoitv-code** [kjk/edna#21]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
Typing something and closing right away doesn't save the changes, so there is the risk to lose the latest changes if typing something and closing right away

**Describe the solution you'd like**

Attaching to the `beforeunload` event to save the changes there if any, eventually displaying an alert for unsaved changes if necessary

**Additional context**
Current behavior seems to automatically save changes every 3-4 seconds, which causes some data loss if closing right after typing something

**Comment by kjk** [comment]
We already do that: https://github.com/kjk/edna/blob/main/src/components/App.svelte#L172

**Comment by benoitv-code** [comment]
Ok then maybe I can re-open it as a bug?

On Chrome, opening the tab, typing "test", closing the tab, then re-opening: the new content (the "test" word) is not there anymore.

No alert is shown. Same behavior on website and PWA app, using folder storage.

**Comment by benoitv-code** [comment]
I think it might be because the tab is closing too fast, so the async functions don't have time to run.

Might want to convert it into a sync version, checking if there are unsaved changes (in a synchronous way), then showing the unsaved changes dialog if it's the case and doing running the async save after that:

```typescript
    // Recommended
    event.preventDefault();

    // Included for legacy support, e.g. Chrome/Edge < 119
    event.returnValue = true;
```

**Comment by benoitv-code** [comment]
@kjk Tested 2156c60, still getting the issue. IMO with an async save you won't be able to make it work without doing a `event.preventDefault();` and showing a popup (as gmail and others do).

But it'll need to have a concept to check if an editor has unsaved changes so it doesn't get too annoying by showing up during every close.

PS: Thanks a lot of the software (and to heynote contributors too), it's great!

**Comment by kjk** [comment]
Thanks for the info. I would prefer to just save the doc but I can't figure out how to make it work so warning dialog it is

**Comment by benoitv-code** [comment]
02b9c20 works well, thanks for the fix! Alert dialog is much prefered to a data loss :)

**Comment by benoitv-code** [comment]
> I haven't yet tried this:
> 
> ```js
> window.onunload = () => {
>   myAsyncFunction().then(() => {
>     // do something after the function has finished running
>   }).catch(error => {
>     console.error(error);
>   });
> };
> ```

IMO it's equivalent to the code that was there before. As soon as an async execution is met for file saving, then the tab being closed will happen before the rest of the async operation can be executed.

I don't think there is an alternative to showing a dialog in this case.

I've left a suggestion for a tiny improvement here: https://github.com/kjk/edna/commit/02b9c204e8713ad8f77c13b27d88d0439fecaea2#r143801353
