### ISSUE TITLE
Feature request: Install instruction for self hosting

### ISSUE THREAD

**Issue by f8dca** [kjk/edna#31]
Great App - I am looking forward to using it !!!

It would be very nice to have some sort of installation guide for installing EDNA on a local server in environments that cannot use public servers.

Beside an install guide, it would be beneficial to remove the hard-coded server parameters in your code and make the entire solution fully parametric - see [12-factor](https://12factor.net/)

Probably a simple docker container would make things easier for a lot of people.

Cheers

G.

**Comment by kjk** [comment]
You must have bun installed.
Then:
* `bun install`
* `go run .\server\ -build-local-prod`
* that generates `edna-<YYYY-MM-DD>-<HASH>` binary that you can run e.g. on my windows it would be `.\edna-2024-07-04-f21bf45.exe -run-prod`
* you can also cross-compile it

Edna is a single executable that you can run anywhere: your windows, your mac, your linux server.

As far as making it easy for others: I really don't know what other people's needs and constraints are. I'll accept PRs to make build easy for others but I'm not going to guess what it means for people.

**Comment by f8dca** [comment]
Thank you for the instructions. It looks simple, and I can certainly try.

I'm just wondering about what is the purpose of the server/deploy.go file ?
It does contain some hard-coded parameters that will be unique for each install.

Thanks

G.

**Comment by f8dca** [comment]
build fails with:  
panic: open ..\secrets\edna.env: The system cannot find the path specified.

**Comment by kjk** [comment]
I've made some fixes and updated `README.md` with build / run instructions. Let me know if they don't work for you.

As to `deploy.go` it's just a deploy system I use for all my apps. It doesn't do anything fancy (compile the binary, copy binary to the server, configure the server, launch the app) but it's specific to my config so just ignore it.

Use the build instructions in readme.md to get a binary but if you want to deploy it to a server, it's up to you to copy it to the server and configure things.

It's probably trivial to deploy this to render.com
