### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by jots** [kjk/edna#4]
**Describe the bug**
Go to https://edna.arslexis.io/
page is blank.

devtools shows this error:

Uncaught (in promise) TypeError: localStorage.setTime is not a function
    at qy (index-BnGHFt-O.js:605:2543)
    at wa (index-BnGHFt-O.js:605:2665)
    at lr (index-BnGHFt-O.js:647:11834)

browser: Version 125.0.6422.76

works in firefox.

**Comment by kjk** [comment]
Thanks for letting me know. If you re-fresh the page it should be fixed.

**Comment by jots** [comment]
Thank you!  Edna is cool!
