### ISSUE TITLE
Bug: Command Palette not accessible on Firefox macOS due to builtin shortcut overlap

### ISSUE THREAD

**Issue by masonc15** [kjk/edna#69]
Hi,

I am using Edna on Firefox on macOS. The Edna hotkey for Command Palette is `⌘ + Shift + P` but this is the [Firefox builtin hotkey](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) for "New Private Window". These builtin keyboard shortcuts cannot be disabled or remapped unfortunately, so I am unable to use the Command Palette in Edna.

I didn't see any settings option to remap Edna hotkeys, which would be my first thought for an easy workaround. Any help would be appreciated. Thanks!

**Comment by kjk** [comment]
You can also use: 
* `Ctrl + K`, `Ctrl + Shift + K`
* `Ctrl + O`, `Ctrl + Shift + O`

See https://edna.arslexis.io/help
