### ISSUE TITLE
Bug: package-lock.json should not be gitignore'd

### ISSUE THREAD

**Issue by hmnd** [kjk/edna#71]
**Describe the bug**
`package-lock.json`, as well as `yarn.lock`, and `bun.lockdb` should not be present in `.gitignore`, to ensure dependencies remain stable and builds remain reproducible.

**Expected behavior**
`package-lock.json` (or the lockfile created by _some_ package manager) is committed to repo.

**Comment by NoahAndrews** [comment]
Can you share your reasoning for closing this?

**Comment by kjk** [comment]
I use bun, there's no package.json

**Comment by hmnd** [comment]
In that case `bun.lockb` should be committed.

**Comment by NoahAndrews** [comment]
Did you mean to close this again?
