### ISSUE TITLE
Feature request: Remove backend? 

### ISSUE THREAD

**Issue by ThomasOrlita** [kjk/edna#77]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
Considering this is primarily a client-side web app, is there a reason for having a Go backend in the first place?

**Describe the solution you'd like**
It seems that the APIs configured in the backend could be moved to the client-side (like calling the Go Playground or Currency APIs). This would then allow to just build this project as a static HTML bundle vs needing to deploy it as a docker container.

**Describe alternatives you've considered**

**Additional context**

**Comment by kjk** [comment]
It's possible but I won't be working on that.

I have a standardized way of deploying all my projects, including Edna.

I'll accept changes for optional no backend build.

BTW: it doesn't require docker. I deploy it as a Go binary. Someone contributed optional Docker build so I've added it.

**Comment by kjk** [comment]
closing as I'm not planning to work on this
